database:
    driver: postgres
    username: postgres
    password: postgres
    host: localhost
    port: 5432
    dbname: agartha
cache:
    host: localhost:6379
    password: ""
    database-selection: 1